"""Measure impact precision/recall on tests/impact/corpus and write docs/accuracy.md.

Ground truth is a marker comment on every truly affected line:
    `// affected: response.property.removed` or `# affected: rule.a, rule.b`
Every unmarked line is truly unaffected.

Run: python tests/impact/accuracy.py
"""

import re
from dataclasses import dataclass
from pathlib import Path

from breakscope.contracts import load_contract
from breakscope.impact import Confidence, analyze
from breakscope.impact.models import ImpactReport

ROOT = Path(__file__).parents[2]
CORPUS = Path(__file__).parent / "corpus"
DOC = ROOT / "docs" / "accuracy.md"
_MARKER = re.compile(r"(?://|#|/\*|<!--)\s*affected:\s*([\w.,\s]+?)\s*(?:\*/\}?|-->)?\s*$")

Location = tuple[str, int, str]  # (file, line, rule)


@dataclass(frozen=True)
class Score:
    threshold: Confidence
    true_positives: int
    detected: int
    truth: int

    @property
    def precision(self) -> float:
        return self.true_positives / self.detected if self.detected else 1.0

    @property
    def recall(self) -> float:
        return self.true_positives / self.truth if self.truth else 1.0


def ground_truth() -> set[Location]:
    truth: set[Location] = set()
    for path in sorted(CORPUS.rglob("*")):
        if path.suffix not in (".py", ".ts", ".tsx", ".js", ".html"):
            continue
        rel = path.relative_to(CORPUS).as_posix()
        for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            m = _MARKER.search(line)
            if m:
                for rule in m.group(1).split(","):
                    truth.add((rel, n, rule.strip()))
    return truth


def run() -> ImpactReport:
    return analyze(
        load_contract(CORPUS / "api" / "old.yaml"),
        load_contract(CORPUS / "api" / "new.yaml"),
        CORPUS,
    )


def detected(report: ImpactReport, threshold: Confidence) -> set[Location]:
    return {
        (i.file, i.line, i.change.rule)
        for i in report.impacts
        if i.confidence.rank <= threshold.rank
    }


def score(report: ImpactReport, truth: set[Location], threshold: Confidence) -> Score:
    found = detected(report, threshold)
    return Score(threshold, len(found & truth), len(found), len(truth))


def render(report: ImpactReport, truth: set[Location]) -> str:
    rows = [score(report, truth, t) for t in (Confidence.HIGH, Confidence.MEDIUM, Confidence.LOW)]
    lines = [
        "# Impact accuracy",
        "",
        "Measured on [`tests/impact/corpus`](../tests/impact/corpus): a small TypeScript, React,",
        "Angular and Python codebase written against `api/old.yaml`, analyzed against",
        "`api/new.yaml`. Every truly affected line carries an `affected:` marker comment.",
        "",
        "Generated by `python tests/impact/accuracy.py`. CI fails if this file is stale or if",
        "precision at the default threshold drops below 100%.",
        "",
        "| Shown at confidence | Precision | Recall | Found / truly affected |",
        "|---|---|---|---|",
    ]
    for s in rows:
        label = {"high": "high only", "medium": "medium+ (default)", "low": "low+"}
        lines.append(
            f"| {label[s.threshold.value]} | {s.precision:.0%} | {s.recall:.0%} "
            f"| {s.true_positives} / {s.truth} |"
        )
    missed = sorted(truth - detected(report, Confidence.LOW))
    lines += ["", "## Known misses", ""]
    if missed:
        lines.append("Truly affected lines that no confidence level finds:")
        lines.append("")
        lines += [f"- `{f}:{n}` ({rule})" for f, n, rule in missed]
    else:
        lines.append("None.")
    return "\n".join(lines) + "\n"


def main() -> None:
    DOC.write_text(render(run(), ground_truth()), encoding="utf-8")
    print(f"wrote {DOC}")


if __name__ == "__main__":
    main()
