from pathlib import Path

import pytest
from tree_sitter import Parser

from breakscope.analyzers.generated import OperationIndex, client_calls, is_generated
from breakscope.analyzers.javascript import _LANGS, JavaScriptAnalyzer
from breakscope.analyzers.python import _LANG as PY_LANG
from breakscope.contracts import load_contract

SPEC = Path(__file__).parents[1] / "impact" / "corpus" / "api" / "old.yaml"


@pytest.mark.parametrize(
    "header",
    [
        b"/* generated using openapi-typescript-codegen -- do not edit */",
        b"// Code generated by orval. DO NOT EDIT.",
        b"# Generated by openapi-python-client",
        b"/**\n * Shop API\n * NOTE: This class is auto generated by OpenAPI Generator",
        b"// @generated",
    ],
)
def test_generated_headers(header: bytes) -> None:
    assert is_generated(header + b"\nexport class X {}")


def test_handwritten_code_is_not_generated() -> None:
    src = b"import axios from 'axios';\n// Generates a report of users.\nexport const x = 1;\n"
    assert not is_generated(src)


def index(generated: bytes) -> OperationIndex:
    return OperationIndex(load_contract(SPEC), [generated])


def test_index_only_knows_ids_that_generated_code_defines() -> None:
    idx = index(b"export class UsersService { static getUser() {} }")
    assert idx.lookup("getUser") == ("GET", "/users/{id}")
    assert idx.lookup("get_user") == ("GET", "/users/{id}")  # any naming style
    assert idx.lookup("listOrders") is None  # not in the generated code


@pytest.mark.parametrize(
    ("src", "expected"),
    [
        ("const u = await UsersService.getUser(1);", "generated:UsersService.getUser"),
        ("const u = await usersApi.getUser(1);", "generated:usersApi.getUser"),  # typescript-axios
        ("const u = await getUser(1);", "generated:getUser"),  # orval-style function
    ],
)
def test_ts_client_calls(src: str, expected: str) -> None:
    source = src.encode()
    root = Parser(_LANGS["typescript"]).parse(source).root_node
    idx = index(b"getUser")
    (site,) = client_calls(root, source, "a.ts", "typescript", idx, is_test=False)
    assert (site.client, site.method, site.url and site.url.path) == (expected, "GET", "/users/{}")


def test_python_client_module_call() -> None:
    source = b"u = get_user.sync(client=c, id=1)\nother.sync()\n"
    root = Parser(PY_LANG).parse(source).root_node
    sites = client_calls(root, source, "a.py", "python", index(b"def get_user"), is_test=False)
    assert [(s.line, s.method) for s in sites] == [(1, "GET")]


def test_unrelated_names_do_not_match() -> None:
    source = b"getUserLabel(u); this.getUsers(); fetchUser(1);"
    root = Parser(_LANGS["typescript"]).parse(source).root_node
    assert client_calls(root, source, "a.ts", "typescript", index(b"getUser"), is_test=False) == []


def test_openapi_fetch_uppercase_verbs_and_braced_params() -> None:
    src = b'const { data } = await client.GET("/users/{id}", { params: { path: { id } } });'
    (site,) = JavaScriptAnalyzer("typescript").scan(src, "a.ts", is_test=False)
    assert (site.method, site.url and site.url.path) == ("GET", "/users/{}")
