# Generated by openapi-python-client. Do not edit.
from typing import Any

import httpx


def _get_kwargs(id: int) -> dict[str, Any]:
    return {"method": "get", "url": f"/users/{id}"}


def sync(*, client: httpx.Client, id: int) -> dict:
    return client.request(**_get_kwargs(id)).json()
