"""Markdown report for PR comments and job summaries."""

from breakscope import __version__
from breakscope.changes import Severity
from breakscope.contracts.rules import RULES
from breakscope.impact.models import Impact, ImpactReport, Risk
from breakscope.reports import ChangeGroup, group_changes
from breakscope.reports.impact import overall_risk

# The PR comment is found and updated by this marker, so there is only ever one.
MARKER = "<!-- breakscope-report -->"
_ICON = {Risk.HIGH: "🔴", Risk.MEDIUM: "🟡", Risk.LOW: "⚪"}
_MAX_LOCATIONS = 10


def render(report: ImpactReport, impacts: list[Impact], *, link_base: str | None = None) -> str:
    groups = group_changes(report.changes)
    breaking = [g for g in groups if g.severity is Severity.BREAKING]
    warnings = [g for g in groups if g.severity is Severity.WARNING]
    locations = len({(i.file, i.line) for i in impacts})
    risk = overall_risk(impacts)

    out = [MARKER]
    if not groups:
        out += ["## ✅ BreakScope: no API contract changes", ""]
        return _footer(out)
    if not breaking and risk is None:
        out.append("## ✅ BreakScope: no breaking API changes")
    else:
        icon = _ICON[risk] if risk else "🟢"
        out.append(
            f"## {icon} BreakScope: {_n(len(breaking), 'breaking API change')}, "
            f"{_n(locations, 'affected location')}"
        )
    out.append("")
    if risk is not None:
        files = len({i.file for i in impacts})
        out.append(f"**Risk: {risk.value.upper()}** · {_n(files, 'file')} affected")
        out.append("")

    for n, g in enumerate(breaking, 1):
        out += _group(n, g, impacts, report, link_base)
    if warnings:
        out += ["<details>", f"<summary>{_n(len(warnings), 'warning')}</summary>", ""]
        for n, g in enumerate(warnings, len(breaking) + 1):
            out += _group(n, g, impacts, report, link_base)
        out += ["</details>", ""]
    return _footer(out)


def _group(
    n: int, g: ChangeGroup, impacts: list[Impact], report: ImpactReport, link_base: str | None
) -> list[str]:
    c = g.first
    group_impacts = [i for i in impacts if i.change in g.changes]
    if len(g.changes) == 1:
        op = f"{c.method} {c.path}"
        rest = c.message[len(op) :] if c.message.startswith(op) else f": {c.message}"
        title = f"`{op}`{_md(rest)}"
    else:
        ops = ", ".join(f"`{x.method} {x.path}`" for x in g.changes[:3])
        more = f" and {len(g.changes) - 3} more" if len(g.changes) > 3 else ""
        title = f"`{c.subject}`: {_md(RULES[c.rule].description)} In {ops}{more}."
    lines = [f"### {n}. {title}", ""]
    if not group_impacts:
        calls = sum(report.call_counts.get(x.key, 0) for x in g.changes)
        lines.append(
            f"_Called in {_n(calls, 'place')}, but no traced reads._"
            if calls and c.field_path
            else "_No affected code found._"
        )
        lines.append("")
        return lines
    lines += ["| | Location | Code | Confidence |", "|---|---|---|---|"]
    for i in group_impacts[:_MAX_LOCATIONS]:
        loc = f"{i.file}:{i.line}"
        loc_md = (
            f"[`{loc}`]({link_base.rstrip('/')}/{i.file}#L{i.line})" if link_base else f"`{loc}`"
        )
        test = " (test)" if i.is_test else ""
        lines.append(
            f"| {_ICON[i.risk]} | {loc_md}{test} | {_code(i.code)} | {i.confidence.value} |"
        )
    if len(group_impacts) > _MAX_LOCATIONS:
        lines.append(f"| | _…and {len(group_impacts) - _MAX_LOCATIONS} more_ | | |")
    lines.append("")
    return lines


def _footer(out: list[str]) -> str:
    out += [
        "<sub>Confidence: <b>high</b> = data flow traced from the API call · <b>medium</b> = "
        "through a function return, component prop or service · <b>low</b> = name match only."
        f' Generated by <a href="https://github.com/Himanshu1281/breakscope">BreakScope</a> '
        f"{__version__}.</sub>",
    ]
    return "\n".join(out) + "\n"


def _n(k: int, word: str) -> str:
    return f"{k} {word}" if k == 1 else f"{k} {word}s"


def _md(s: str) -> str:
    return s.replace("|", "\\|")


def _code(code: str) -> str:
    """A code span for a table cell. Code containing backticks gets a double-backtick
    span, which may hold single backticks; pipes are escaped for the table."""
    code = code.replace("|", "\\|")
    if "``" in code:
        code = code.replace("`", "'")  # rare; keep the table intact
    if "`" in code:
        return f"`` {code} ``"
    return f"`{code}`"
